--Tabela de chats (conversas)
CREATE TABLE CHATS(
	ID_CHAT SERIAL PRIMARY KEY,
	DT_CHAT TIMESTAMP,
	NR_PERGUNTAS INT,
	NR_RESPOSTAS INT
);

--Tabela de procedimentos e leis
CREATE TABLE PROCEDIMENTOS(
	ID_PROCEDIMENTO SERIAL PRIMARY KEY,
	NM_PROCEIMENTO VARCHAR(50)
);

--Tabela intermediária de procedimentos de um chat
CREATE TABLE PROCEDIMENTOS_CHAT(
	ID_PROCEDIMENTOS_CHAT SERIAL PRIMARY KEY,
	CD_CHAT INT,
	CD_PROCEDIMENTO INT,
	
	FOREIGN KEY (CD_CHAT) REFERENCES CHATS(ID_CHAT),
    FOREIGN KEY (CD_PROCEDIMENTO) REFERENCES PROCEDIMENTOS(ID_PROCEDIMENTO)
);

--Tabela de controle de tokens
CREATE TABLE CONTROLE(
	ID_CONTROLE SERIAL PRIMARY KEY,
	CD_CHAT INT,
	NR_TOKENS INT,
	VL_TOKENS DECIMAL,

	FOREIGN KEY (CD_CHAT) REFERENCES CHATS(ID_CHAT)
);